/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.42
 * Generated at: 2022-05-24 05:57:28 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.*;
import co.jp.netwisdom.dto.UserinfoHobbyDto;

public final class userReg_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=utf-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<html>\r\n");
      out.write("  <head>\r\n");
      out.write("    <title>用户注册画面</title>\r\n");
      out.write("    <script>\r\n");
      out.write("        function changeActionName(actionName){\r\n");
      out.write("        \tdocument.getElementById(\"form\").action = actionName ;\r\n");
      out.write("        \tdocument.getElementById(\"username\").disabled = false;\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("    </script>\r\n");
      out.write("  </head>\r\n");
      out.write("\r\n");
      out.write("  ");
 UserinfoHobbyDto dto = (UserinfoHobbyDto)request.getAttribute("dto"); 
      out.write("\r\n");
      out.write("  ");
if(dto != null){ 
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("\t<form action=\"userUpdate\"  id = \"form\">\r\n");
      out.write("\t\t姓名:<input disabled  id=\"username\" name=\"username\" value =\"");
      out.print(dto.getUsername());
      out.write("\" ><br>\r\n");
      out.write("\t\t密码:<input type=\"password\" id=\"password\" name = \"password\" value = \"");
      out.print(dto.getPassword());
      out.write("\"><br>\r\n");
      out.write("\t\t性别:<input type=\"radio\" name=\"sex\" checked  id=\"sex1\" value=\"0\" ");
if("0".equals(dto.getSex())){
      out.write(" checked ");
} 
      out.write(" >男\r\n");
      out.write("\t\t<input type=\"radio\"  name=\"sex\" id=\"sex2\"  value=\"1\" ");
if("1".equals(dto.getSex())){
      out.write(" checked ");
} 
      out.write(">女<br>\r\n");
      out.write("\t\t爱好:\r\n");
      out.write("\t\t<input type=\"checkbox\" name=\"hobby\" value=\"0\" ");
if(dto.getHobbys().contains("0")){
      out.write(" checked ");
} 
      out.write(">足球\r\n");
      out.write("\t\t<input type=\"checkbox\" name=\"hobby\" value=\"1\" ");
if(dto.getHobbys().contains("1")){
      out.write(" checked ");
} 
      out.write(">篮球\r\n");
      out.write("\t\t<input type=\"checkbox\" name=\"hobby\" value=\"2\" ");
if(dto.getHobbys().contains("2")){
      out.write(" checked ");
} 
      out.write(">网球\r\n");
      out.write("\t\t<br>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t专业:<select id=\"major1\" name = \"major\">\r\n");
      out.write("\t\t\t<option value=\"0\" ");
if("0".equals(dto.getMajor())){
      out.write(" selected ");
} 
      out.write(">软件工程</option>\r\n");
      out.write("\t\t\t<option value=\"1\" ");
if("1".equals(dto.getMajor())){
      out.write(" selected ");
} 
      out.write(">英语</option>\r\n");
      out.write("\t\t\t<option value=\"2\" ");
if("2".equals(dto.getMajor())){
      out.write(" selected ");
} 
      out.write(">数学</option>\r\n");
      out.write("\t\t</select><br>\r\n");
      out.write("\t\t简介:<br><textarea id=\"intro1\"  name=\"intro\">");
      out.print(dto.getIntro());
      out.write("</textarea><br>\r\n");
      out.write("\t\t \r\n");
      out.write("\t\t<input type=\"submit\" value=\"更新用户\" onclick = \"changeActionName('userUpdate')\">\r\n");
      out.write("\t\t<input type=\"submit\" value=\"删除用户\" onclick = \"changeActionName('userDel')\">\r\n");
      out.write("\t\t<input type=\"button\" value=\"重置\">\r\n");
      out.write("\t</form>\r\n");
      out.write("</body>\r\n");
}else{
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("\t<form action=\"userRegister\" >\r\n");
      out.write("\t\t姓名:<input id=\"username\" name=\"username\"  ><br>\r\n");
      out.write("\t\t密码:<input type=\"password\" id=\"password\" name = \"password\"><br>\r\n");
      out.write("\t\t性别:<input type=\"radio\" name=\"sex\" checked  id=\"sex1\" value=\"0\" checked >男\r\n");
      out.write("\t\t<input type=\"radio\"  name=\"sex\" id=\"sex2\"  value=\"1\" >女<br>\r\n");
      out.write("\t\t爱好:\r\n");
      out.write("\t\t<input type=\"checkbox\" name=\"hobby\" value=\"0\" >足球\r\n");
      out.write("\t\t<input type=\"checkbox\" name=\"hobby\" value=\"1\" >篮球\r\n");
      out.write("\t\t<input type=\"checkbox\" name=\"hobby\" value=\"2\" >网球\r\n");
      out.write("\t\t<br>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t专业:<select id=\"major1\" name = \"major\">\r\n");
      out.write("\t\t\t<option value=\"0\" >软件工程</option>\r\n");
      out.write("\t\t\t<option value=\"1\" >英语</option>\r\n");
      out.write("\t\t\t<option value=\"2\" >数学</option>\r\n");
      out.write("\t\t</select><br>\r\n");
      out.write("\t\t简介:<br><textarea id=\"intro1\"  name=\"intro\"></textarea><br>\r\n");
      out.write("\t\t \r\n");
      out.write("\t\t<input type=\"submit\" value=\"注册用户\">\r\n");
      out.write("\t\t<input type=\"button\" value=\"重置\">\r\n");
      out.write("\t</form>\r\n");
      out.write("</body>\r\n");
      out.write("\r\n");
      out.write("\r\n");
 }
      out.write("\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
