/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.42
 * Generated at: 2022-05-25 07:16:49 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.*;

public final class zlsearch_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=utf-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<html>\r\n");
      out.write("  <head>\r\n");
      out.write("    <title>练习查询</title>\r\n");
      out.write("  </head>\r\n");
      out.write("  <body>\r\n");
      out.write("    <form action=\"zlsearch\" name=\"form\">\r\n");
      out.write("\t           姓名：<input type = \"text\" id =\"username\" name = \"username\"><br/>\r\n");
      out.write("\t           性别：<input type = \"radio\" id = \"sex1\" name=\"sex\" value =\"0\" checked>男\r\n");
      out.write("\t        <input type = \"radio\" id = \"sex2\" name=\"sex\" value =\"1\" >女<br/>\r\n");
      out.write("\t           专业：<select name=\"major\">\r\n");
      out.write("\t           <option value=\"\"></option>\r\n");
      out.write("\t           <option value=\"1\">软件工程</option>\r\n");
      out.write("\t           <option value=\"1\">数学</option>\r\n");
      out.write("\t           <option value=\"1\">英语</option>\r\n");
      out.write("\t        </select><br/>\r\n");
      out.write("\t     <input type=\"submit\" value =\"检索\"><br/><br/>\r\n");
      out.write("\t           检索一览\r\n");
      out.write("\t    <hr>\r\n");
      out.write("\t    <center>\r\n");
      out.write("\t    <table border = 1px style=\"width:80% ; text-align:center\">\r\n");
      out.write("\t       <tr>\r\n");
      out.write("\t         <td>姓名</td>\r\n");
      out.write("\t         <td>密码</td>\r\n");
      out.write("\t         <td>性别</td>\r\n");
      out.write("\t         <td>爱好</td>\r\n");
      out.write("\t         <td>专业</td>\r\n");
      out.write("\t         <td>简介</td>\r\n");
      out.write("\t       </tr>\r\n");
      out.write("\t    </table>\r\n");
      out.write("\t    </center>\r\n");
      out.write("\t     \r\n");
      out.write("    </form>\r\n");
      out.write("  </body>\r\n");
      out.write("</html>\r\n");
      out.write("\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
